// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ENSX1YUsIepAw1xhmLqUqShND4QS6kM',
    appId: '1:602596509591:web:d36a8cd458e917cc3aa6d2',
    messagingSenderId: '602596509591',
    projectId: 'spendwise2',
    authDomain: 'spendwise2.firebaseapp.com',
    storageBucket: 'spendwise2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl28-mjivwJimdCmPA2e3jQrWyceJOkNY',
    appId: '1:602596509591:android:309058c5f3a315c23aa6d2',
    messagingSenderId: '602596509591',
    projectId: 'spendwise2',
    storageBucket: 'spendwise2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMfX8D684nGYF1iLFITa0tqOMnm4fBwyc',
    appId: '1:602596509591:ios:d7377e3b2b536ad33aa6d2',
    messagingSenderId: '602596509591',
    projectId: 'spendwise2',
    storageBucket: 'spendwise2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMfX8D684nGYF1iLFITa0tqOMnm4fBwyc',
    appId: '1:602596509591:ios:d7377e3b2b536ad33aa6d2',
    messagingSenderId: '602596509591',
    projectId: 'spendwise2',
    storageBucket: 'spendwise2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ENSX1YUsIepAw1xhmLqUqShND4QS6kM',
    appId: '1:602596509591:web:24c5076da6113be13aa6d2',
    messagingSenderId: '602596509591',
    projectId: 'spendwise2',
    authDomain: 'spendwise2.firebaseapp.com',
    storageBucket: 'spendwise2.firebasestorage.app',
  );
}
